---
- name: Build app image
  hosts: localhost
  become: true

  tasks:
    - name: Check if Docker is installed
      ansible.builtin.stat:
        path: /var/lib/docker
      register: docker_check

    - name: Install Docker if not installed
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /home/ubuntu/get-docker.sh
      when: docker_check.stat.exists == False

    - name: Install Docker
      ansible.builtin.command: sudo sh /home/ubuntu/get-docker.sh 
      when: docker_check.stat.exists == False

    - name: Ensure that Docker is started
      ansible.builtin.service:
        name: docker
        state: started
  
    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip 

    - name: Install Docker SDK for python
      ansible.builtin.pip:
        name: docker 
     
    - name: Delete existing Docker images from the Control Node
      ansible.builtin.command: docker rmi $(docker images -q) -f 
      ignore_errors: yes

    - name: create docker image
      community.general.docker_image:
        name: Noteapp
        build:
          path: /home/ubuntu/workspace/NoteApp
          pull: true
        state: present
        tag: "latest"
        force_tag: yes
        repository: prototyp97/Noteapp:latest
        push: yes
        source: build