---
- name: Update and Installation
  hosts: all
  become: true

  tasks:
    - name: Update the VM
      ansible.builtin.apt:
        update_cache: yes

    - name: Check if Docker is installed
      ansible.builtin.stat:
        path: /var/lib/docker
      register: docker_check

    - name: Install Docker if not installed
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /home/ubuntu/get-docker.sh
      when: docker_check.stat.exists == False

    - name: Install Docker
      ansible.builtin.script:
        src: /home/ubuntu/get-docker.sh
      when: docker_check.stat.exists == False

    - name: Ensure that Docker is started
      ansible.builtin.service:
        name: docker
        state: started
