---
- name: Copy and Start App
  hosts: all
  become: true 
  
  tasks:
    - name: Copy app dir noteapp to remote host
      ansible.builtin.copy:
        src: ~/workspace/NoteApp
        dest: ~/NoteApp
        
    - name: Delete existing Docker images from the Control Node
      ansible.builtin.command: docker rmi $(docker images -q) -f 
      ignore_errors: yes

    - name: Executing the command
      ansible.builtin.command: docker compose up --build -d
      args:
        chdir: "~/NoteApp/NoteApp" 
        
