---
- name: Build app image
  hosts: localhost
  become: true

  tasks:
    - name: Check if Docker is installed
      ansible.builtin.stat:
        path: /var/lib/docker
      register: docker_check

    - name: Install Docker if not installed
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /home/ubuntu/get-docker.sh
      when: docker_check.stat.exists == False

    - name: Install Docker
      ansible.builtin.command: sudo sh /home/ubuntu/get-docker.sh 
      when: docker_check.stat.exists == False

    - name: Ensure that Docker is started
      ansible.builtin.service:
        name: docker
        state: started
  
    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip 

    - name: Install Docker SDK for python
      ansible.builtin.pip:
        name: docker-py 
     
    - name: Delete existing Docker images from the Control Node
      ansible.builtin.command: docker rmi $(sudo docker images -q) -f 
      ignore_errors: yes

    - name: create docker image
      ansible.builtin.command: docker build -d -t prototyp97/noteapp:latest .
      args:
        chdir: /home/ubuntu/workspace/NoteApp@3 
    
    - name: push image to Dockerhub
      ansible.builtin.command: docker push prototyp97/noteapp:latest

    