---
- name: Update and Installation
  hosts: all
  become: true

  tasks:
    - name: Update the VM
      ansible.builtin.apt:
        update_cache: yes

    - name: Check if Docker is installed
      ansible.builtin.stat:
        path: /var/lib/docker
      register: docker_check

    - name: Install Docker if not installed
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /home/ubuntu/get-docker.sh
      when: docker_check.stat.exists == False

    - name: Install Docker
      ansible.builtin.script:
        src: /home/ubuntu/get-docker.sh
      when: docker_check.stat.exists == False

    - name: Ensure that Docker is started
      ansible.builtin.service:
        name: docker
        state: started

    - name: Pull image from Dockerhub
      ansible.builtin.command: docker pull prototyp97/noteapp:latest

  
    - name: Delete existing Docker contener
      ansible.builtin.command: docker rm $(sudo docker ps -q) -f 
      ignore_errors: yes

    - name: Create conteneur
      ansible.builtin.command: docker run -it -d -p 8080:80 -p 5432:5432 --name noteapp-web-01 prototyp97/noteapp:latest



